name: form_inputs
description: A simple in memory cache made for dart
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  # formz: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
