name: app_provider
description: Control the whole app provider operation with the Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  #
  flutter:
    sdk: flutter
  provider: ^6.0.1
  flutter_bloc: ^8.1.1

  components:
    path: ../components
  remote_data:
    path: ../firebase
  local_database:
    path: ../local_data
  isumi:
    path: ../../
